### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by larialberti** [felipetoffolo1/hugofy-atom#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.2 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [hugofy](https://github.com/felipetoffolo1/hugofy-atom) package 2.0.0

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /home/larissa/.atom/packages/hugofy/lib/hugofy.js:78

ReferenceError: path is not defined
    at Object.createFile (/packages/hugofy/lib/hugofy.js:78:34)
    at /packages/hugofy/lib/hugofy.js:40:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -9:20.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
 26x -9:17.7.0 core:backspace (input.hidden-input)
  2x -7:08.4.0 markdown-writer:toggle-bold-text (input.hidden-input)
  2x -4:05.5.0 core:backspace (input.hidden-input)
     -3:35.7.0 core:move-right (input.hidden-input)
     -3:26.9.0 core:save (input.hidden-input)
undefined -3:24.3.0 core:move-down (input.hidden-input)
  9x -3:13.6.0 core:move-up (input.hidden-input)
     -0:59.2.0 command-palette:toggle (input.hidden-input)
     -0:56.8.0 core:confirm (input.hidden-input)
     -0:56.8.0 application:show-preferences (input.hidden-input)
 23x -0:30 core:backspace (input.hidden-input)
     -0:25.6.0 core:confirm (input.hidden-input)
  3x -0:14.4.0 core:backspace (input.hidden-input)
     -0:11.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
hugofy 2.0.0 
markdown-writer 2.6.3 
tool-bar 1.0.1 
tool-bar-markdown-writer 0.2.0 
```

**Comment by anherrera** [comment]
Also seeing this on OSX 10.12.6

/Users/alexa/.atom/packages/hugofy/lib/hugofy.js:78


ReferenceError: path is not defined
    at Object.createFile (/Users/alexa/.atom/packages/hugofy/lib/hugofy.js:78:29)
    at HTMLElement.coreConfirm (/Users/alexa/.atom/packages/hugofy/lib/hugofy.js:40:40)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)

**Comment by jm3** [comment]
Still seeing this in 2018 on

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [hugofy](https://github.com/felipetoffolo1/hugofy-atom) package 2.0.0

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /Users/jm3/.atom/packages/hugofy/lib/hugofy.js:78

ReferenceError: path is not defined
    at Object.createFile (/packages/hugofy/lib/hugofy.js:78:29)
    at HTMLElement.coreConfirm (/packages/hugofy/lib/hugofy.js:40:40)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350121)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1212648)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1208782)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285300)
```

### Commands

```
     -1:03.3.0 command-palette:toggle (div.tool-panel.tree-view)
  2x -1:01.5.0 core:move-down (input.hidden-input)
     -1:00.4.0 core:move-up (input.hidden-input)
     -1:00.1.0 core:confirm (input.hidden-input)
     -1:00.1.0 hugofy:stopServer (div.tool-panel.tree-view)
     -0:55.9.0 command-palette:toggle (div.tool-panel.tree-view)
     -0:55.1.0 editor:consolidate-selections (input.hidden-input)
     -0:55.1.0 core:cancel (input.hidden-input)
     -0:54.6.0 core:close (div.tool-panel.tree-view)
     -0:50.1.0 command-palette:toggle (input.hidden-input)
     -0:48.3.0 core:confirm (input.hidden-input)
     -0:48.3.0 hugofy:startServer (input.hidden-input)
     -0:44.3.0 settings-view:open (input.hidden-input)
     -0:26.1.0 find-and-replace:show (select#atom-hugo.site.format.form-control)
  6x -0:25.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-hugo 0.1.2 
git-plus 8.6.2 
hugofy 2.0.0 
language-hugo 0.5.1 
minimap 4.29.9 
minimap-lens 0.2.0 
scroll-through-time 0.3.1 
sort-lines 0.19.0 
sync-settings 0.8.6 
terminal-tab 0.5.7 
todo-show 2.3.2 
Wild-Cherry 0.10.0 
```
